### ISSUE TITLE
Nitrous users generally struggle with this

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/hello-world-ruby#51]
Many Nitrous users seem to struggle on this lab. Maybe because they're unfamiliar with how to navigate around? They often are just in the wrong directory, etc. 

It might be worth breaking out separate instructions or adding Nitrous hints throughout?

**Comment by PeterBell** [comment]
Hi @sammarcus great feedback. Would like to circle round with @AnnJohn on this. I think including nitrous notes on each class would be distracting for other users. Just because we're considering sunsetting nitrous pretty soon, I'm going to close this for now, but I agree that if we don't do that, we probably need to have some more content - maybe in the "intro to learn - nitrous" course to get students up to speed and comfortable.
